name: Test & Deploy

on:
  push:
    branches:
      - main
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    name: "Test Python ${{ matrix.python-version }} & Django ${{ matrix.django-version }}"
    services:
      postgres95:
        image: postgres:9.5
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5495:5432
      postgres96:
        image: postgres:9.6
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5496:5432
      postgres10:
        image: postgres:10
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5410:5432
      postgres11:
        image: postgres:11
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5411:5432
      postgres12:
        image: postgres:12
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5412:5432
      postgres13:
        image: postgres:13
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5413:5432
    strategy:
      matrix:
        django-version: ["2.2", "3.0", "3.1", "3.2"]
        python-version: ["3.5", "3.6", "3.7", "3.8", "3.9"]
        exclude:
          # 3.0
          - django-version: "3.0"
            python-version: "3.5"
          # 3.1
          - django-version: "3.1"
            python-version: "3.5"
          # 3.2
          - django-version: "3.2"
            python-version: "3.5"
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - uses: actions/cache@v2
        name: Configure pip caching
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('setup.py') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install dependencies
        run: |
          python -m pip install -U pip
          python -m pip install Django~=${{ matrix.django-version }}.0
          python -m pip install '.[test]'
      - name: Run tests
        run: |
          coverage run "$(command -v django-admin.py)" test --pythonpath . -v 2 --settings=tests.settings
          coverage report
        env:
          PG_VERSIONS: "95,96,10,11,12,13"
      - name: Upload coverage to codecov.io
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
      - uses: actions/upload-artifact@v2
        with:
          name: "screnshots-py${{ matrix.python-version }}-dj${{ matrix.django-version }}"
          path: tests/output/
          if-no-files-found: error
          retention-days: 1
      - name: Post screenshots
        if: "${{ github.event_name == 'pull_request' &&  matrix.python-version == '3.9' && matrix.django-version == '3.2' }}"
        run: |
          python -m pip install imgbox-cli
          imgbox --json tests/output/*.png > imgbox-response.json
          python post_screenshot_comment.py "$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")" "$(readlink -f imgbox-response.json)"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: Install dependencies
        run: |
          python -m pip install -U pip
          python -m pip install -r docs/requirements.txt
      - name: Generate and test API docs
        run: |
          make html
        env:
          SPHINXOPTS: "-n -v -W --keep-going"
        working-directory: ./docs

  deploy:
    if: ${{ github.event_name == 'push' && contains(github.ref, 'refs/tags/') }}
    runs-on: ubuntu-latest
    needs: [test, docs]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - uses: actions/cache@v2
        name: Configure pip caching
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-publish-pip-${{ hashFiles('setup.py') }}
          restore-keys: |
            ${{ runner.os }}-publish-pip-
      - name: Install dependencies
        run: |
          pip install -U pip
          python -m pip install setuptools wheel twine
      - name: Publish
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
        run: |
          python setup.py sdist bdist_wheel
          twine upload dist/*
      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
